sonar.projectKey=transfer-platform
sonar.projectName=transfer-platform
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}
